<a href="https://colab.research.google.com/github/Spandan-Singh/Python_training/blob/main/numpyDemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np


In [ ]:
len(dir(np))

603

In [ ]:
np.pi

3.141592653589793

In [ ]:
mileage_avg = np.average([10,18,20])
mileage_avg

16.0

In [ ]:
mileage_avg *1.1

17.6

In [ ]:
vec_a = np.array([12,45,78,34])

In [ ]:
mat_a = np.array([
    [11,12,13,14],
    [21,22,23,24],
    [31,32,33,34]
])

mat_a

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [ ]:
vec_a.shape

(4,)

In [ ]:

n_rows, n_cols = mat_a.shape

In [ ]:
n_rows

3

In [ ]:
n_cols

4

In [ ]:
vec_b = np.array(["abc", "xyz"])

In [ ]:
vec_b.dtype

dtype('<U3')

In [ ]:
vec_a.dtype


dtype('int64')

In [ ]:
mat_a +100

array([[111, 112, 113, 114],
       [121, 122, 123, 124],
       [131, 132, 133, 134]])

In [ ]:
mat_a+[100,200,300,400]

array([[111, 212, 313, 414],
       [121, 222, 323, 424],
       [131, 232, 333, 434]])

In [ ]:
vec_a
mat_a + vec_a

array([[ 23,  57,  91,  48],
       [ 33,  67, 101,  58],
       [ 43,  77, 111,  68]])

In [ ]:
mat_a[:1, 1:2]

array([[12]])

In [ ]:
mat_a[:2, 1:3
      ]

array([[12, 13],
       [22, 23]])

In [ ]:
mat_a[:40, 1:3]

array([[12, 13],
       [22, 23],
       [32, 33]])

In [ ]:
mat_a[mat_a % 2 == 0]

array([12, 14, 22, 24, 32, 34])

In [ ]:
[mat_a%2==0]

[array([[False,  True, False,  True],
        [False,  True, False,  True],
        [False,  True, False,  True]])]

In [ ]:
mat_a[mat_a % 2 == 0].reshape(3,2)

array([[12, 14],
       [22, 24],
       [32, 34]])

In [ ]:
two_z = np.array([[11,12],[21,22],[31,32]])

In [ ]:
two_z.shape


(3, 2)

In [ ]:
np.sum(two_z, axis=0)

array([63, 66])

In [ ]:
np.sum(two_z, axis=1
       )

array([23, 43, 63])

In [ ]:
points = np.array([[ 0, 11],
       [ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15]])

In [ ]:
observation = np.array([2.8, 12.5])

In [ ]:
points - observation


array([[-2.8, -1.5],
       [-1.8, -0.5],
       [-0.8,  0.5],
       [ 0.2,  1.5],
       [ 1.2,  2.5]])

In [ ]:
(points - observation) ** 2


array([[7.84, 2.25],
       [3.24, 0.25],
       [0.64, 0.25],
       [0.04, 2.25],
       [1.44, 6.25]])

In [ ]:
np.sum((points - observation) ** 2, axis =1) ** 5


array([1.04581732e+05, 5.17758378e+02, 5.58405945e-01, 6.29763392e+01,
       2.68925323e+04])

In [ ]:
np.sum((points - observation) ** 2, axis =1)


array([10.09,  3.49,  0.89,  2.29,  7.69])

In [ ]:
dist = np.sqrt(np.sum((points - observation) ** 2, axis =1))

In [ ]:
idx = dist.argmin()

In [ ]:
idx

2

In [ ]:
points[idx]

array([ 2, 13])